# Generated by Django 5.0 on 2026-02-13 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=30)),
                ('installed_date', models.DateField()),
                ('last_maintenance', models.DateField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='ships.ship')),
            ],
        ),
    ]
