# Generated by Django 5.0 on 2026-02-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ipl_logo/'),
        ),
    ]
