# Generated by Django 5.0 on 2026-02-03 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0002_alter_franchise_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveBigIntegerField()),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('Wicket-Keeper', 'Wicket-Keeper'), ('All-Rounder', 'All-Rounder')], max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_app.franchise')),
            ],
        ),
    ]
