# Generated by Django 5.0 on 2026-02-03 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0003_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_app.franchise')),
            ],
        ),
    ]
