# Generated by Django 5.0 on 2026-02-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_ready',
            new_name='is_read',
        ),
    ]
